name: Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          # macOS
          - os: macos
            arch: x64
            runner: macos-13
            artifact: tumiki-proxy-macos-x64
          - os: macos
            arch: arm64
            runner: macos-14
            artifact: tumiki-proxy-macos-arm64
          # Linux
          - os: linux
            arch: x64
            runner: ubuntu-latest
            artifact: tumiki-proxy-linux-x64
          # Windows
          - os: windows
            arch: x64
            runner: windows-latest
            artifact: tumiki-proxy-win-x64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build TypeScript
        run: bun run build

      - name: Build binary with Bun
        run: bun build src/index.ts --compile --target=bun --outfile ${{ matrix.artifact }}

      - name: Make binary executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x ${{ matrix.artifact }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
